<a href="https://colab.research.google.com/github/20192931/AImobility/blob/main/3_3_%EA%B3%B5%EA%B3%B5%EB%8D%B0%EC%9D%B4%ED%84%B0__%ED%86%A8%EA%B2%8C%EC%9D%B4%ED%84%B0_%EA%B5%90%ED%86%B5%EB%9F%89.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 공공데이터에서 '실시간 교통량'으로 검색: https://www.data.go.kr/data/15076872/openapi.do

### **공공데이터 활용하기 _ 실시간 교통량**

1. https://www.data.go.kr/
2. 공공데이터 포털 -> 실시간 영엉소별 교통량 검색 -> 고속도로 공공데이터 포털로 바로가기 -> 데이터 활용 -> 인증키 발급 -> 메일발송 
3. 공공데이터 포털 
   * URL  복사 
   * 참고 문서 다운로드

### **01. API Key 준비하기**

In [ ]:
pip install requests

In [ ]:
import requests
import pandas as pd

In [ ]:
url = "http://data.ex.co.kr/openapi/odtraffic/trafficAmountByUnit"

In [ ]:
# 본인의 키 사용
key = "6489867226"

### **02. 여러 톨게이트 + 하나의 시간대 검색하기**

In [ ]:
params ={'key' : key, 'type' :'xml', 
         'sumTmUnitTypeCode':'3',
         'stdHour' : '13', 'numOfRows' : '1000', 
         'pageNo' : '1'}

In [ ]:
response = requests.get(url, params=params)

In [ ]:
response.content

b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><data><code>SUCCESS</code><message>\xec\x9d\xb8\xec\xa6\x9d\xed\x82\xa4\xea\xb0\x80 \xec\x9c\xa0\xed\x9a\xa8\xed\x95\xa9\xeb\x8b\x88\xeb\x8b\xa4.</message><count>0</count><numOfRows>99</numOfRows><pageNo>1</pageNo><pageSize>0</pageSize></data>'

In [ ]:
# requests가 response의 인코딩 방식을 자동으로 인식
print(response.apparent_encoding)

utf-8

In [ ]:
type(response.content)

bytes

In [ ]:
data = str(response.content,"utf-8")
data

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><data><code>SUCCESS</code><message>인증키가 유효합니다.</message><count>0</count><numOfRows>99</numOfRows><pageNo>1</pageNo><pageSize>0</pageSize></data>'

### **03. xml Parsing 하기**

#### **01. 파싱하기**

In [ ]:
import xml.etree.ElementTree as ET

In [ ]:
tree = ET.fromstring(data)
tree # 객체가 반환된다.

#### **2. 데이터 확인**

In [ ]:
len(tree)

6

In [ ]:
list(tree)

[<Element 'code' at 0x7f83eacaf040>,
 <Element 'message' at 0x7f83eac55a40>,
 <Element 'count' at 0x7f83eac55a90>,
 <Element 'numOfRows' at 0x7f83eac55ae0>,
 <Element 'pageNo' at 0x7f83eac55b30>,
 <Element 'pageSize' at 0x7f83eac55b80>]

In [ ]:
new_data = tree[5]
print(len(new_data))
print(new_data)

0
<Element 'pageSize' at 0x7f83eac55b80>

In [ ]:
for i in range (len(new_data)):
    print(new_data[i].tag,new_data[i].text, i)

In [ ]:
for a in range (3, 102):
    new_data = tree[a]
    print(new_data[1].text, new_data[3].text, new_data[4].text, 
          new_data[5].text, new_data[6].text, new_data[7].text, 
          new_data[8].text, new_data[9].text, new_data[10].text, 
          new_data[12].text, new_data[13].text, new_data[11].tag, new_data[11].text)

IndexError: ignored

#### **3. 필요한 데이터 가져오기**

In [ ]:
df = []
for a in range(3, 102):
    temp = []
    # 4번(입구출구), 11번(톨게이트이름), 13번(교통량) 열만 사용
    for b in [4, 11, 13]:     
        temp.append(tree[a][b].text)
    df.append(temp)

df

[['입구', '7', '북천안'],
 ['입구', '8', '북천안'],
 ['출구', '8', '북천안'],
 ['입구', '20', '북천안'],
 ['출구', '13', '북천안'],
 ['출구', '101', '옥산'],
 ['입구', '70', '옥산'],
 ['입구', '1', '옥산'],
 ['입구', '379', '남청주'],
 ['출구', '468', '남청주'],
 ['입구', '4', '남청주'],
 ['출구', '1', '남청주'],
 ['입구', '7', '남청주'],
 ['출구', '6', '남청주'],
 ['출구', '4', '남청주'],
 ['입구', '4', '남청주'],
 ['입구', '2', '남청주'],
 ['출구', '7', '남청주'],
 ['입구', '11', '남청주'],
 ['출구', '16', '남청주'],
 ['입구', '580', '신탄진'],
 ['출구', '688', '신탄진'],
 ['입구', '5', '신탄진'],
 ['출구', '3', '신탄진'],
 ['입구', '2', '신탄진'],
 ['출구', '11', '신탄진'],
 ['출구', '4', '신탄진'],
 ['입구', '2', '신탄진'],
 ['입구', '9', '신탄진'],
 ['출구', '7', '신탄진'],
 ['입구', '23', '신탄진'],
 ['출구', '37', '신탄진'],
 ['입구', '1362', '대전'],
 ['출구', '1471', '대전'],
 ['출구', '4', '대전'],
 ['입구', '37', '대전'],
 ['출구', '39', '대전'],
 ['입구', '1', '대전'],
 ['출구', '2', '대전'],
 ['출구', '2', '대전'],
 ['입구', '2', '대전'],
 ['입구', '51', '대전'],
 ['출구', '71', '대전'],
 ['입구', '639', '북대전'],
 ['출구', '656', '북대전'],
 ['출구', '1', '북대전'],
 ['입구', '11', '북대전'],
 ['출구', '13', '북대전'],
 ['입구', '2', '북대전'],
 ['출구', '2', '북대전'],
 ['출구', '6', '북대전'],
 ['입구', '9', '북대전'],
 ['입구', '20', '북대전'],
 ['출구', '24', '북대전'],
 ['입구', '1044', '유성'],
 ['출구', '1329', '유성'],
 ['입구', '6', '유성'],
 ['출구', '5', '유성'],
 ['입구', '24', '유성'],
 ['출구', '15', '유성'],
 ['출구', '1', '유성'],
 ['입구', '2', '유성'],
 ['입구', '2', '유성'],
 ['출구', '1', '유성'],
 ['입구', '26', '유성'],
 ['출구', '50', '유성'],
 ['입구', '413', '옥천'],
 ['출구', '466', '옥천'],
 ['출구', '2', '옥천'],
 ['입구', '1', '옥천'],
 ['출구', '5', '옥천'],
 ['입구', '2', '옥천'],
 ['출구', '2', '옥천'],
 ['출구', '7', '옥천'],
 ['입구', '1', '옥천'],
 ['입구', '17', '옥천'],
 ['출구', '23', '옥천'],
 ['입구', '36', '금강'],
 ['출구', '62', '금강'],
 ['입구', '2', '금강'],
 ['입구', '2', '금강'],
 ['출구', '4', '금강'],
 ['출구', '116', '영동'],
 ['입구', '127', '영동'],
 ['출구', '1', '영동'],
 ['입구', '1', '영동'],
 ['출구', '1', '영동'],
 ['입구', '2', '영동'],
 ['입구', '6', '영동'],
 ['출구', '4', '영동'],
 ['출구', '619', '판암'],
 ['입구', '603', '판암'],
 ['입구', '5', '판암'],
 ['입구', '4', '판암'],
 ['출구', '1', '판암'],
 ['출구', '2', '판암'],
 ['출구', '2', '판암'],
 ['입구', '30', '판암'],
 ['출구', '33', '판암']]

In [ ]:
# 데이터프레임으로 만들기
df = pd.DataFrame(df)
df.head()

    0   1    2
0  입구   7  북천안
1  입구   8  북천안
2  출구   8  북천안
3  입구  20  북천안
4  출구  13  북천안

#### **4. 데이터 처리하기**

In [ ]:
# 데이터프레임 열 이름 바꾸기
df.columns = ['exit', 'volume', 'toll']
df.head(3)

  exit volume toll
0   입구      7  북천안
1   입구      8  북천안
2   출구      8  북천안

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   exit    99 non-null     object
 1   volume  99 non-null     object
 2   toll    99 non-null     object
dtypes: object(3)
memory usage: 2.4+ KB

In [ ]:
# volume 열은 합계를 내야 하므로 정수형으로 변경
df['volume'] = df['volume'].astype(int)

**iloc** : integer location의 약어, 데이터 프레임의 행이나 칼럼의 순서를 나타내는 정수로 특정 값을 추출해오는 방법
* 데이터프레임명.iloc[행인덱스, 열인덱스]

---

In [ ]:
# 출구만 추려내기
df = df[df.iloc[:, 0] == '출구']
df

   exit  volume toll
2    출구       8  북천안
4    출구      13  북천안
5    출구     101   옥산
9    출구     468  남청주
11   출구       1  남청주
13   출구       6  남청주
14   출구       4  남청주
17   출구       7  남청주
19   출구      16  남청주
21   출구     688  신탄진
23   출구       3  신탄진
25   출구      11  신탄진
26   출구       4  신탄진
29   출구       7  신탄진
31   출구      37  신탄진
33   출구    1471   대전
34   출구       4   대전
36   출구      39   대전
38   출구       2   대전
39   출구       2   대전
42   출구      71   대전
44   출구     656  북대전
45   출구       1  북대전
47   출구      13  북대전
49   출구       2  북대전
50   출구       6  북대전
53   출구      24  북대전
55   출구    1329   유성
57   출구       5   유성
59   출구      15   유성
60   출구       1   유성
63   출구       1   유성
65   출구      50   유성
67   출구     466   옥천
68   출구       2   옥천
70   출구       5   옥천
72   출구       2   옥천
73   출구       7   옥천
76   출구      23   옥천
78   출구      62   금강
81   출구       4   금강
82   출구     116   영동
84   출구       1   영동
86   출구       1   영동
89   출구       4   영동
90   출구     619   판암
94   출구       1   판암
95   출구       2   판암
96   출구       2   판암
98   출구      33   판암

In [ ]:
# 'toll' 열 기준으로 group by하는데, 'volume' 열에 대해서만 합계 함수를 적용
traffic = df.groupby('toll')['volume'].sum()
df_traffic = pd.DataFrame(traffic)
df_traffic

      volume
toll
금강        66
남청주      502
대전      1589
북대전      702
북천안       21
신탄진      750
영동       122
옥산       101
옥천       505
유성      1401
판암       657

#### **5. 그래프 그리기**

In [ ]:
# 한글을 지원하는 plotly 간단한 코드로 그리기
import plotly.express as px

fig = px.bar(
    df_traffic, 
    y="volume",
    width=800,
    height=450,
    title='톨게이트별 교통량')

fig.show()

In [ ]:
# 참고 : plotly에 옵션 많이 넣어서 그리기
import plotly.express as px

fig = px.bar(
    traffic, 
    y="volume",
    width=800,
    height=450,
    labels={'toll': '톨게이트','volume': '교통량'},  # 또는 그냥 y만 바꾸기 --> {'y': '교통량'} 
    title='톨게이트별 교통량')

# 배경색 설정
fig.update_layout(
    plot_bgcolor='lightpink', 
    paper_bgcolor='gainsboro',
    title={'x': 0.5}  # 제목을 가운데 보여주기. 0(왼쪽) ~ 1(오른쪽)
)
fig.show()

### **04.한 톨게이트 + 여러 시간대**

#### **1. 데이터 가져오기**

In [ ]:
params ={'key' : key, 'type' :'xml', 'sumTmUnitTypeCode':'3', 
         'stdHour' : '07', 'numOfRows' : '1000'}    
response = requests.get(url, params=params)
data = str(response.content,"utf-8")
data

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><data><code>SUCCESS</code><message>인증키가 유효합니다.</message><count>4248</count><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>1197</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>896</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>36</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>19</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>21</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>24</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>16</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>5</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>5</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>5종</tcsCarTypeNm><trafficAmout>27</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>5</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>5종</tcsCarTypeNm><trafficAmout>26</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>83</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>51</trafficAmout><unitCode>011 </unitCode><unitName>인천</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>1070</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>1343</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>21</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>37</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>54</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>65</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>18</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>29</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>5</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>5종</tcsCarTypeNm><trafficAmout>18</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>5</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>5종</tcsCarTypeNm><trafficAmout>24</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>76</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210100</brofCode><brofName>인천</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>77</trafficAmout><unitCode>068 </unitCode><unitName>김포</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>334</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>560</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>2</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>7</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>51</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>28</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>2</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>1</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>5</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>5종</tcsCarTypeNm><trafficAmout>3</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>29</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>17</trafficAmout><unitCode>102 </unitCode><unitName>동수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>76</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>83</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>4</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>6</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>3</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>3종</tcsCarTypeNm><trafficAmout>6</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>3</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>4</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>4종</tcsCarTypeNm><trafficAmout>1</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>5</tcsCarTypeCd><tcsCarTypeGrpCd>3</tcsCarTypeGrpCd><tcsCarTypeGrpNm>대형차</tcsCarTypeGrpNm><tcsCarTypeNm>5종</tcsCarTypeNm><trafficAmout>1</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>2</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>6</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>6종</tcsCarTypeNm><trafficAmout>8</trafficAmout><unitCode>171 </unitCode><unitName>마성</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>167</trafficAmout><unitCode>212 </unitCode><unitName>북수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>1</tcsCarTypeCd><tcsCarTypeGrpCd>1</tcsCarTypeGrpCd><tcsCarTypeGrpNm>소형차</tcsCarTypeGrpNm><tcsCarTypeNm>1종</tcsCarTypeNm><trafficAmout>342</trafficAmout><unitCode>212 </unitCode><unitName>북수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>출구</inoutName><stdDate>20221225</stdDate><stdHour>07  </stdHour><tcsCarTypeCd>2</tcsCarTypeCd><tcsCarTypeGrpCd>2</tcsCarTypeGrpCd><tcsCarTypeGrpNm>중형차</tcsCarTypeGrpNm><tcsCarTypeNm>2종</tcsCarTypeNm><trafficAmout>6</trafficAmout><unitCode>212 </unitCode><unitName>북수원</unitName></list><list><brofCode>210200</brofCode><brofName>군포</brofName><centerCode>901</centerCode><centerName>수도권본부</centerName><inoutName>입구</inoutName><stdDate>20221225</stdDate><stdHour>07  

In [ ]:
tree = ET.fromstring(data)
print(len(tree))

105

In [ ]:
for a in range (30):  # 30까지만 하면 김포는 나오므로
    new_data = tree[a]
    for b in range (len(new_data)):
        print(new_data[b].text, end=' ')
    print()

210100 인천 901 수도권본부 입구 20221225 07   1 1 소형차 1종 1197 011  인천
210100 인천 901 수도권본부 출구 20221225 07   1 1 소형차 1종 896 011  인천
210100 인천 901 수도권본부 입구 20221225 07   2 2 중형차 2종 36 011  인천
210100 인천 901 수도권본부 출구 20221225 07   2 2 중형차 2종 19 011  인천
210100 인천 901 수도권본부 입구 20221225 07   3 3 대형차 3종 21 011  인천
210100 인천 901 수도권본부 출구 20221225 07   3 3 대형차 3종 24 011  인천
210100 인천 901 수도권본부 출구 20221225 07   4 3 대형차 4종 16 011  인천
210100 인천 901 수도권본부 입구 20221225 07   4 3 대형차 4종 5 011  인천
210100 인천 901 수도권본부 입구 20221225 07   5 3 대형차 5종 27 011  인천
210100 인천 901 수도권본부 출구 20221225 07   5 3 대형차 5종 26 011  인천
210100 인천 901 수도권본부 입구 20221225 07   6 1 소형차 6종 83 011  인천
210100 인천 901 수도권본부 출구 20221225 07   6 1 소형차 6종 51 011  인천
210100 인천 901 수도권본부 입구 20221225 07   1 1 소형차 1종 1070 068  김포
210100 인천 901 수도권본부 출구 20221225 07   1 1 소형차 1종 1343 068  김포
210100 인천 901 수도권본부 입구 20221225 07   2 2 중형차 2종 21 068  김포
210100 인천 901 수도권본부 출구 20221225 07   2 2 중형차 2종 37 068  김포
210100 인천 901 수도권본부 입구 20221225 07   3 3 대형차 3종 54 068  김포
210100 인천 901 수도권본부 출구 20221225 07   3 3 대형차 3종 65 068  김포
210100 인천 901 수도권본부 출구 20221225 07   4 3 대형차 4종 18 068  김포
210100 인천 901 수도권본부 입구 20221225 07   4 3 대형차 4종 29 068  김포
210100 인천 901 수도권본부 입구 20221225 07   5 3 대형차 5종 18 068  김포
210100 인천 901 수도권본부 출구 20221225 07   5 3 대형차 5종 24 068  김포
210100 인천 901 수도권본부 입구 20221225 07   6 1 소형차 6종 76 068  김포
210100 인천 901 수도권본부 출구 20221225 07   6 1 소형차 6종 77 068  김포
210200 군포 901 수도권본부 출구 20221225 07   1 1 소형차 1종 334 102  동수원
210200 군포 901 수도권본부 입구 20221225 07   1 1 소형차 1종 560 102  동수원
210200 군포 901 수도권본부 출구 20221225 07   2 2 중형차 2종 2 102  동수원

In [ ]:
# 데이터를 Element 'list'에서 뽑아내기
df = []
for a in range(3, 25):
    temp = []
    # 4번(입구출구), 6번(기준시), 10번(차종), 11번(톨게이트이름), 13번(교통량) 열사용: 위와 비교하여 6번이 추가되었어요
    for b in [4, 6, 10, 11, 13]:     
        temp.append(tree[a][b].text)
    df.append(temp)

df

[['입구', '07  ', '1종', '1197', '인천'],
 ['출구', '07  ', '1종', '896', '인천'],
 ['입구', '07  ', '2종', '36', '인천'],
 ['출구', '07  ', '2종', '19', '인천'],
 ['입구', '07  ', '3종', '21', '인천'],
 ['출구', '07  ', '3종', '24', '인천'],
 ['출구', '07  ', '4종', '16', '인천'],
 ['입구', '07  ', '4종', '5', '인천'],
 ['입구', '07  ', '5종', '27', '인천'],
 ['출구', '07  ', '5종', '26', '인천'],
 ['입구', '07  ', '6종', '83', '인천'],
 ['출구', '07  ', '6종', '51', '인천'],
 ['입구', '07  ', '1종', '1070', '김포'],
 ['출구', '07  ', '1종', '1343', '김포'],
 ['입구', '07  ', '2종', '21', '김포'],
 ['출구', '07  ', '2종', '37', '김포'],
 ['입구', '07  ', '3종', '54', '김포'],
 ['출구', '07  ', '3종', '65', '김포'],
 ['출구', '07  ', '4종', '18', '김포'],
 ['입구', '07  ', '4종', '29', '김포'],
 ['입구', '07  ', '5종', '18', '김포'],
 ['출구', '07  ', '5종', '24', '김포']]

In [ ]:
# 데이터프레임으로 만들기
df7 = pd.DataFrame(df)
df7.head(3)

    0     1   2     3   4
0  입구  07    1종  1197  인천
1  출구  07    1종   896  인천
2  입구  07    2종    36  인천

#### **2. 함수로 만들기**

#### 1) 함수를 시간대별로 여러번 호출하기

In [ ]:
def hourly(hour):
    params ={'key' : key, 'type' :'xml', 'sumTmUnitTypeCode':'3', 
             'stdHour' : hour, 'numOfRows' : '1000', 'pageNo' : '10'}    
    response = requests.get(url, params=params)
    data = str(response.content,"utf-8")
    tree = ET.fromstring(data)
    df = []
    
    for a in range(3, 25):
        temp = []
        # 4번(입구출구), 6번(기준시), 10번(차종), 11번(톨게이트이름), 13번(교통량) 열사용: 위와 비교하여 6번이 추가되었어요
        for b in [4, 6, 10, 11, 13]:     
            temp.append(tree[a][b].text)
        df.append(temp)
    df = pd.DataFrame(df) 

    return df

In [ ]:
df5 = hourly('05')
df5.head(3)

    0     1   2   3   4
0  입구  05    6종   1  송악
1  출구  05    6종   5  송악
2  출구  05    1종  47  당진

In [ ]:
df6 = hourly('06')
df6.head(3)

    0     1   2   3   4
0  출구  06    6종   9  유성
1  입구  06    1종  51  옥천
2  출구  06    1종  78  옥천

In [ ]:
df7 = hourly('07')
df7.head(3)

    0     1   2    3    4
0  출구  07    1종  107  북천안
1  입구  07    2종   12  북천안
2  출구  07    2종    8  북천안

In [ ]:
# df 합치기
df = pd.concat([df5, df6, df7])
df

#### 2) 여러 시간대를 돌리는 함수 만들기

In [ ]:
def many_hours(hour_list):
    dfs = pd.DataFrame([])

    for i in hour_list:   
        df = hourly(i)
        dfs = pd.concat([dfs, df])
    
    return dfs

In [ ]:
# 뽑을 시간대의 목록을 여기에 입력
hour_list = ['05', '06', '07', '08', '09', '10', '11', '15', '16'] 

df = many_hours(hour_list)

In [ ]:
df

     0     1   2   3    4
0   입구  05    6종   1   송악
1   출구  05    6종   5   송악
2   출구  05    1종  47   당진
3   입구  05    1종  40   당진
4   입구  05    2종   1   당진
..  ..   ...  ..  ..  ...
17  출구  16    2종   7  신탄진
18  입구  16    2종   2  신탄진
19  입구  16    3종   4  신탄진
20  출구  16    3종   6  신탄진
21  출구  16    4종   8  신탄진

[198 rows x 5 columns]

#### **03. 데이터 처리**

1) 데이터 프레임 열 이름 바꾸기

In [ ]:
# 데이터프레임 열 이름 바꾸기
df.columns = ['exit', 'hour', 'type', 'volume', 'toll']
df.head()

  exit  hour type volume toll
0   입구  05     6종      1   송악
1   출구  05     6종      5   송악
2   출구  05     1종     47   당진
3   입구  05     1종     40   당진
4   입구  05     2종      1   당진

2) 데이터 타입 바꾸기

In [ ]:
df['volume'] = df['volume'].astype(int)

3) 데이터 추출하기

In [ ]:
# 출구 & 김포  데이터 추출하기
df_dangjin = df[(df.loc[:, 'exit'] == '출구') & (df.loc[:, 'toll'] == '당진')]
df_dangjin

  exit  hour type  volume toll
2   출구  05     1종      47   당진
6   출구  05     4종       2   당진
9   출구  05     6종       6   당진

#### **04. 데이터 그래프 그리기**

## 막대그래프

In [ ]:
traffic1 = df.groupby('hour')['volume'].sum()
df1_traffic = pd.DataFrame( traffic1 )

df1_traffic

      volume
hour
05       265
06       364
07       523
08       439
09      1144
10       911
11      1038
15      1390
16      2635

In [ ]:
# plotly 간단한 코드로 그리기: (결과 분석할 때 평일인지, 주말인지 감안 필요해요)
import plotly.express as px

fig = px.bar(
    df1_traffic, 
    y='volume',
    width=800,
    height=450,
    title='당진 톨게이트 시간대별 교통량')

fig.show()